include: package:lints/recommended.yaml

analyzer:
  exclude: 
    - example/explorer/**
    # - lib/src/**/*.dart
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors: 
    todo: info
      
linter:
  rules:
    # Some additional lints we want to enforce
    omit_local_variable_types: true
    prefer_expression_function_bodies: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_interpolation_to_compose_strings: true
    prefer_relative_imports: true
    sort_unnamed_constructors_first: true
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true

    # We name Win32 constants for consistency with Win32, not Dart
    constant_identifier_names: false
    non_constant_identifier_names: false
    camel_case_types: false

    # We use `this` to minimize the risk of name clashes
    unnecessary_this: false

    # COM interop classes are named for their contents
    file_names: false
